{% set version = "1.12" %}

package:
  name: flask-compress
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Flask-Compress/Flask-Compress-{{ version }}.tar.gz
  sha256: e2159499f39d618a4d56ba0484e7b58b57956b9a2c6d3510f095f5bb14b7afc5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.6
    - setuptools-scm
  run:
    - brotli-python
    - flask
    - python >=2.7|>=3.6

test:
  source_files:
    - tests
  imports:
    - flask_compress
  commands:
    - pip list
    - pip list | grep "Flask-Compress\s*{{ version.replace(".", "\.") }}"
    - pip check
    - pytest -vv tests
  requires:
    - m2-grep  # [win]
    - pip
    - pytest

about:
  home: https://github.com/colour-science/flask-compress
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compress responses in your Flask app with gzip.
  description: |
    Flask-Compress allows you to easily compress your Flask application's responses with gzip.
  dev_url: https://github.com/colour-science/flask-compress

extra:
  recipe-maintainers:
    - synapticarbors
    - mariusvniekerk
