{% set version = "1.15" %}

package:
  name: flask-compress
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/F/Flask-Compress/flask_compress-{{ version }}.tar.gz
  sha256: b7b66cd5d08fc46bbcc71561e13ca64321590b0ca4c172f8001bf5374f8f5c58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.6
    - setuptools-scm
  run:
    - brotli-python
    - flask
    - python >=2.7|>=3.6

test:
  source_files:
    - tests
  imports:
    - flask_compress
  commands:
    - pip list
    - pip list | grep "Flask-Compress\s*{{ version.replace(".", "\.") }}"
    - pip check
    - pytest -vv tests
  requires:
    - m2-grep  # [win]
    - pip
    - pytest

about:
  home: https://github.com/colour-science/flask-compress
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compress responses in your Flask app with gzip.
  description: |
    Flask-Compress allows you to easily compress your Flask application's responses with gzip.
  dev_url: https://github.com/colour-science/flask-compress

extra:
  recipe-maintainers:
    - synapticarbors
    - mariusvniekerk
