{% set name = "Flask-Compress" %}
{% set version = "1.12" %}
{% set sha256 = "e2159499f39d618a4d56ba0484e7b58b57956b9a2c6d3510f095f5bb14b7afc5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =2.7|>=3.6
    - pip
    - setuptools_scm >=3.4
  run:
    - python >=2.7|>=3.6
    - flask
    - brotli-python

test:
  source_files:
    - tests
  imports:
    - flask_compress
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/colour-science/flask-compress
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compress responses in your Flask app with gzip.

  description: |
    Flask-Compress allows you to easily compress your Flask application's responses with gzip.
  dev_url: https://github.com/colour-science/flask-compress

extra:
  recipe-maintainers:
    - synapticarbors
    - mariusvniekerk
