{% set version = "1.18" %}

package:
  name: flask-compress
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Flask-Compress/flask_compress-{{ version }}.tar.gz
  sha256: fdbae1bd8e334dfdc8b19549829163987c796fafea7fa1c63f9a4add23c8413a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm <8
    - setuptools >=42
  run:
    - brotli
    - brotlicffi
    - pyzstd
    - brotli-python
    - flask
    - zstandard
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - flask_compress
  commands:
    - pip list
    - pip list | grep "Flask-Compress\s*{{ version.replace(".", "\.") }}"
    - pip check
    - pytest -vv tests
  requires:
    - m2-grep  # [win]
    - pip
    - pytest
    - flask-caching
    - python {{ python_min }}

about:
  home: https://github.com/colour-science/flask-compress
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compress responses in your Flask app with gzip.
  description: |
    Flask-Compress allows you to easily compress your Flask application's responses with gzip.
  dev_url: https://github.com/colour-science/flask-compress

extra:
  recipe-maintainers:
    - synapticarbors
    - mariusvniekerk
